#!/bin/bash

print() {
	printf "%s\n" "$1"
	exit 0
}

bluetooth=$(bluetoothctl show | grep Powered | head -n1 | grep yes | awk '{ print $2 }')
state=$(bluetoothctl info | grep Connected | head -n1 | awk '{ print $2 }')

if [[ -n $bluetooth ]]; then
	case "$state" in
		"yes")
			icon="󰂯"
			;;
		*)
			icon="󰂲"
			;;
	esac
else
	icon=""
fi

print "$icon"
