#!/bin/bash

print() {
	printf "%s\n" "$1"
	exit 0
}

eth=$(nmcli device show | grep GENERAL.DEVICE | grep "eth[0-9]" | head -n1 | awk '{ print $2 }')
state=$(nmcli device show "$eth" | grep GENERAL.STATE | awk '{ print $2 }')

if [[ -n $eth ]]; then
	case $state in
		100)
			icon="󰈁"
			;;
		*)
			icon=""
			;;
	esac
else
	icon=""
fi

print "$icon"
